# Generated by Django 2.0.3 on 2018-03-26 06:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_perasitamol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ketorolac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_name', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=30)),
                ('price', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
