# Generated by Django 2.0.3 on 2018-03-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_ceftriaxone_fexofenadine'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='content1',
            field=models.TextField(blank=True),
        ),
    ]
